---
title: "Topic Modeling with r/narcolepsy"
author: "Nicole Blackburn"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(tidytext)
library(RedditExtractoR)
library(quanteda)
library(topicmodels)
```

# Prep

```{r}
data_raw <- read.csv("r_narc_nov11.csv") #read dataset

data <- data_raw |> 
  select("date_utc","timestamp","title","text","comments","url","doc_id") |> 
  relocate("doc_id", .before = "date_utc") |> 
  filter(!is.na(text), text != "") #remove na values in text
```

#topic modeling

```{r}
# create a corpus
corp = corpus(data, docid_field = "doc_id", text_field = "text")

# Tokenization
corp_tokens <- tokens(
  corp,
  remove_punct = TRUE,
  remove_numbers = TRUE,
  remove_symbols = TRUE) %>%
  tokens_tolower()

# Lemmatization
lemmaData <- read.csv2(
  "C:/Users/npbvb/OneDrive - University of Maryland/R_Projects/727/Week 7/baseform_en.tsv",
  sep = "\t",
  header = FALSE,
  encoding = "UTF-8",
  stringsAsFactors = F
)

lemmaData <- na.omit(lemmaData)

corp_tokens <-  tokens_replace(corp_tokens, lemmaData$V1, lemmaData$V2, valuetype = "fixed") 

corp_tokens <- corp_tokens %>%
  tokens_remove(stopwords("english")) %>%
  tokens_ngrams(1) 
#tell computer to ignore "sleep"

#create dtm
DTM = dfm(corp_tokens)

#minimum
minimumFrequency <- 10
DTM <- dfm_trim(DTM, 
                min_docfreq = minimumFrequency)
# keep only letters... brute force
DTM  <- dfm_select(DTM, 
                   pattern = "[a-z]", 
                   valuetype = "regex", 
                   selection = 'keep')
colnames(DTM) <- stringi::stri_replace_all_regex(colnames(DTM), 
                                                 "[^_a-z]","")

DTM <- dfm_compress(DTM, "features")

# We have several rows which do not have any content left. Drop them.

sel_idx <- rowSums(DTM) > 0
DTM <- DTM[sel_idx, ]
corp <- corp[sel_idx, ]
```

```{r}
K <- 15
# Set seed to make results reproducible
set.seed(12)
topicModel <- LDA(DTM, 
                  K, 
                  method="Gibbs", 
                  control=list(iter = 500, 
                               verbose = 25))
```

```{r}
tmResult <- posterior(topicModel)
str(tmResult)

# Topics are distributions over the entire vocabulary

beta <- tmResult$terms
glimpse(beta)            

# Each doc has a distribution over k topics

theta <- tmResult$topics
glimpse(theta)               

terms(topicModel, 10)

# Top terms per topic. Use top 5 to interpret topics
top5termsPerTopic <- terms(topicModel, 
                           5)
# For the next steps, we want to give the topics more descriptive names than just numbers. Therefore, we simply concatenate the five most likely terms of each topic to a string that represents a pseudo-name for each topic.
topicNames <- apply(top5termsPerTopic, 
                    2, 
                    paste, 
                    collapse=" ")
topicNames
```

# tidy text

```{r}
tidy_data <- data |> 
  unnest_tokens(word, text) |> 
  anti_join(stop_words) |> 
  filter(word != "sleep")

tidy_data |> count(word, sort=TRUE) |> head(10)
```

## td-idf

```{r}
tfidf <- tidy_data |> 
  mutate(doc_id = as.character(doc_id)) |> 
  count(doc_id, word, sort = TRUE) |> 
  bind_tf_idf(word, doc_id, n)

tf_top <- tfidf |> 
  group_by(doc_id) |> 
  arrange(desc(tf_idf), .by_group = TRUE) |> 
  slice_head(n = 10) |>
  ungroup()

head(tfidf)

ggplot(aes(word, tf_idf, fill = doc_idc)) +
  geom_col(show.legend = FALSE) +
  coord_flip()
  
  
```
